-   id: textfind
    name: find undesired text in your code
    description: |
        Find undesired text in your code. Use with args  args: ["--text", "unwanted-text", "--text", "my-second-unwanted-text"]
    args: []
    entry: textfind
    language: python
    types: [python]
