-   id: text-find
    name: find undesired text in your code
    description: |
        Find undesired text in your code. Use with args  args: ["--text", "unwanted-text", "--text", "my-second-unwanted-text"]
    args: []
    entry: text-find
    language: script
    types: [python]
